Simplify bootstrapping (#241)
* startup without precompile

* update spacing

* use release mode

* spacing

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,11 +1,19 @@
-#!/usr/bin/env sh
-bank_hash=$(./target/release/solana-ledger-tool -l config/bootstrap-validator bank-hash)
+#!/usr/bin/env bash
+set -eu
+
+BANK_HASH=$(cargo run --release --bin solana-ledger-tool -- -l config/bootstrap-validator bank-hash)
+
+# increase max file handle limit
+ulimit -Hn 1000000
+
+# if above fails, run:
+# sudo bash -c 'echo "*               hard    nofile          1000000" >> /etc/security/limits.conf'
 
 # NOTE: make sure tip-payment and tip-distribution program are deployed using the correct pubkeys
 RUST_LOG=INFO,solana_core::bundle_stage=DEBUG \
-	NDEBUG=1 ./multinode-demo/bootstrap-validator.sh  \
+  NDEBUG=1 ./multinode-demo/bootstrap-validator.sh \
   --wait-for-supermajority 0 \
-  --expected-bank-hash $bank_hash \
+  --expected-bank-hash "$BANK_HASH" \
   --block-engine-address http://127.0.0.1:1003 \
   --block-engine-auth-service-address http://127.0.0.1:1005 \
   --relayer-auth-service-address http://127.0.0.1:11226 \
