ci: reorganize Windows build (#5031)
* ci: refactor publish windows tarball

* ci: trigger windows build in the secondary pipeline

* Update .github/workflows/publish-windows-tarball.yml

Co-authored-by: Will Hickey <csu_hickey@yahoo.com>

---------

Co-authored-by: Will Hickey <csu_hickey@yahoo.com>

diff --git a/.github/workflows/publish-windows-tarball.yml b/.github/workflows/publish-windows-tarball.yml
--- a/.github/workflows/publish-windows-tarball.yml
+++ b/.github/workflows/publish-windows-tarball.yml
@@ -1,14 +1,12 @@
-name: release-artifacts
+name: Publish Windows Tarball
 
 on:
-  workflow_call:
+  workflow_dispatch:
     inputs:
       commit:
-        required: false
         type: string
-    secrets:
-      GCS_RELEASE_BUCKET_WRITER_CREDIENTIAL:
         required: true
+        description: commit
 
 jobs:
   windows-build:
@@ -23,22 +21,6 @@ jobs:
           ref: master
           fetch-depth: 0
 
-      - name: Setup Rust
-        shell: bash
-        run: |
-          source ci/rust-version.sh stable
-
-      # copy the newest version env.sh before switching version.
-      - name: Copy Env Script
-        shell: bash
-        run: |
-          cp -r ci/env.sh /tmp/env.sh
-
-      - name: Switch Version
-        if: ${{ inputs.commit }}
-        run: |
-          git checkout ${{ inputs.commit }}
-
       # took the workaround from https://github.com/sfackler/rust-openssl/issues/2149
       - name: Set Perl environment variables
         run: |
@@ -48,14 +30,30 @@ jobs:
       - name: Build
         id: build
         shell: bash
+        env:
+          COMMIT: ${{ github.event.inputs.commit }}
         run: |
           # install all deps
           source .github/scripts/install-all-deps.sh ${{ runner.os }}
 
-          source /tmp/env.sh
+          # checkout the commit
+          if [[ -z ${{ env.COMMIT }} ]]; then
+            echo "Required parameter env.COMMIT is empty."
+            exit 1
+          fi
+
+          git checkout ${{ env.COMMIT }}
+
+          source ci/env.sh
           echo "tag=$CI_TAG" >> $GITHUB_OUTPUT
           eval "$(ci/channel-info.sh)"
           echo "channel=$CHANNEL" >> $GITHUB_OUTPUT
+
+          # print the info
+          echo "::notice::commit: ${{ env.COMMIT }}"
+          echo "::notice::tag: $CI_TAG"
+          echo "::notice::channel: $CHANNEL"
+
           ci/publish-tarball.sh
 
       - name: Prepare Upload Files
